Migrate to new configuration asciidoc macro and build plugin 5.4.5
micronaut-projects/micronaut-aot pull request #169
Opened 2023-02-07 19:00 UTC by wetted

closes #165

2023-02-08 14:22 UTC, sdelamo approved these changes

2023-02-14 08:28 UTC, melix requested changes

2023-02-14 08:28 UTC, melix commented on src/main/docs/guide/quickStart.adoc
> -```
:x: This must be reverted: this is not a Micronaut configuration file, but the AOT configuration file which is independent and uses only properties files.

2023-02-14 11:28 UTC, sdelamo commented
@wetted please address @melix request changes

2023-02-14 15:32 UTC, melix approved these changes

2023-02-14 15:32 UTC, melix approved these changes

2023-02-22 04:21 UTC, merged